const hitData_10 = {
  level_0: [
    {
      id: 1,
      time: "0' - 1'",
      velocidade: "4-5 km/h",
      esforço: "Fácil",
    },
    {
      id: 2,
      time: "1' - 3'",
      velocidade: "5-6 km/h",
      esforço: "Moderado",
    },
    {
      id: 3,
      time: "3' - 4'",
      velocidade: "6-7 km/h",
      esforço: "Máximo",
    },
    { id: 4, time: "4' - 5'", velocidade: "4-5 km/h", esforço: "Fácil" },
    { id: 5, time: "5' - 6'", velocidade: "5-6 km/h", esforço: "Moderado" },
    { id: 6, time: "6' - 7'", velocidade: "4-5 km/h", esforço: "Fácil" },
    { id: 7, time: "7' - 8'", velocidade: "6-7 km/h", esforço: "Máximo" },
    { id: 8, time: "8' - 9'", velocidade: "5-6 km/h", esforço: "Moderado" },
    { id: 9, time: "9' - 10'", velocidade: "4-5 km/h", esforço: "Fácil" },
  ],
  level_1: [
    { id: 10, time: "0' - 1'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 11, time: "1' - 3'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 12, time: "3' - 4'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 13, time: "4' - 5'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 14, time: "5' - 6'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 15, time: "6' - 7'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 16, time: "7' - 8'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 17, time: "8' - 9'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 18, time: "9' - 10'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
  level_2: [
    { id: 19, time: "0' - 1'", velocidade: "5-6 km/h", esforço: "Fácil" },
    {
      id: 100,
      time: "1' - 3'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    { id: 20, time: "3' - 4'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 21, time: "4' - 5'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 22, time: "5' - 6'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 23, time: "6' - 7'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 24, time: "7' - 8'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 25, time: "8' - 9'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 26, time: "9' - 10'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
  level_3: [
    { id: 27, time: "0' - 1'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 28, time: "1' - 2'", velocidade: "5-6 km/h", esforço: "Moderado" },
    {
      id: 29,
      time: "2' - 3'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 30, time: "3' - 4'", velocidade: "13-15 km/h", esforço: "Máximo" },
    { id: 31, time: "4' - 5'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 32, time: "5' - 6'", velocidade: "13-15 km/h", esforço: "Máximo" },
    { id: 33, time: "6' - 7'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 34, time: "7' - 8'", velocidade: "13-15 km/h", esforço: "Máximo" },
    { id: 35, time: "8' - 9'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 36, time: "9' - 10'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
  level_4: [
    { id: 37, time: "0' - 1'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 38, time: "1' - 2'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 39,
      time: "2' - 3'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    {
      id: 40,
      time: "3' - 4'",
      velocidade: "13-15 km/h",
      esforço: "Forte",
    },
    { id: 41, time: "4' - 5'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 42, time: "5' - 6'", velocidade: "13-15 km/h", esforço: "Forte" },
    {
      id: 43,
      time: "6' - 7'",
      velocidade: "7-8 km/h",
      esforço: "Moderado",
    },
    {
      id: 44,
      time: "7' - 8'",
      velocidade: "16-18 km/h",
      esforço: "Máximo",
    },
    {
      id: 45,
      time: "8' - 9'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    {
      id: 46,
      time: "9' - 10'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
  ],
  level_5: [
    {
      id: 47,
      time: "0' - 1'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
    {
      id: 48,
      time: "1' - 2'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    {
      id: 49,
      time: "2' - 3'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    {
      id: 50,
      time: "3' - 4'",
      velocidade: "16-18 km/h",
      esforço: "Máximo",
    },
    {
      id: 51,
      time: "4' - 5'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
    {
      id: 52,
      time: "5' - 6'",
      velocidade: "16-18 km/h",
      esforço: "Máximo",
    },
    {
      id: 53,
      time: "6' - 7'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    {
      id: 54,
      time: "7' - 8'",
      velocidade: "16-18 km/h",
      esforço: "Máximo",
    },
    { id: 55, time: "8' - 9'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 56, time: "9' - 10'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
};

const hitData_15 = {
  level_0: [
    {
      id: 1,
      time: "0' - 1'",
      velocidade: "4-5 km/h",
      esforço: "Fácil",
    },
    {
      id: 2,
      time: "1' - 3'",
      velocidade: "5-6 km/h",
      esforço: "Moderado",
    },
    {
      id: 3,
      time: "3' - 4'",
      velocidade: "6-7 km/h",
      esforço: "Máximo",
    },
    { id: 4, time: "4' - 5'", velocidade: "5-6 km/h", esforço: "Moderado" },
    {
      id: 5,
      time: "5' - 6'",
      velocidade: "4-5 km/h",
      esforço: "Fácil",
    },
    { id: 6, time: "6' - 7'", velocidade: "6-7 km/h", esforço: "Máximo" },
    { id: 7, time: "7' - 8'", velocidade: "5-6 km/h", esforço: "Moderado" },
    {
      id: 8,
      time: "8' - 9'",
      velocidade: "4-5 km/h",
      esforço: "Fácil",
    },
    { id: 9, time: "9' - 10'", velocidade: "6-7 km/h", esforço: "Máximo" },
    {
      id: 10,
      time: "10' - 11'",
      velocidade: "4-5 km/h",
      esforço: "Fácil",
    },
    { id: 11, time: "11' - 13'", velocidade: "5-6 km/h", esforço: "Moderado" },
    { id: 12, time: "13' - 14'", velocidade: "6-7 km/h", esforço: "Máximo" },
    {
      id: 13,
      time: "14' - 15'",
      velocidade: "4-5 km/h",
      esforço: "Fácil",
    },
  ],
  level_1: [
    { id: 14, time: "0' - 1'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 15, time: "1' - 3'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 16, time: "3' - 4'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 17, time: "4' - 5'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 18, time: "5' - 6'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 19, time: "6' - 7'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 20, time: "7' - 8'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 21, time: "8' - 9'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 22, time: "9' - 10'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 23, time: "10' - 11'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 24, time: "11' - 13'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 25, time: "13' - 14'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 26, time: "14' - 15'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
  level_2: [
    { id: 27, time: "0' - 1'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 28, time: "1' - 3'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 29, time: "3' - 4'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 30, time: "4' - 6'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 31, time: "6' - 7'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 32, time: "8' - 9'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 33, time: "9' - 10'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 34, time: "11' - 12'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 35, time: "12' - 13'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 36, time: "13' - 14'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 37, time: "14' - 15'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
  level_3: [
    { id: 38, time: "0' - 1'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 39, time: "1' - 2'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 40,
      time: "2' - 4'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 41, time: "4' - 5'", velocidade: "13-15 km/h", esforço: "Máximo" },
    { id: 42, time: "5' - 6'", velocidade: "5-6 km/h", esforço: "Fácil" },
    {
      id: 43,
      time: "6' - 8'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    {
      id: 44,
      time: "8' - 9'",
      velocidade: "13-15 km/h",
      esforço: "Máximo",
    },
    { id: 45, time: "9' - 10'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 46, time: "10' - 11'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 47,
      time: "11' - 12'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 48, time: "12' - 13'", velocidade: "13-15 km/h", esforço: "Máximo" },
    { id: 49, time: "13' - 14'", velocidade: "7-8 km/h", esforço: "Moderado" },
    { id: 50, time: "14' - 15'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],

  level_4: [
    { id: 51, time: "0' - 1'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 52, time: "1' - 2'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 53,
      time: "2' - 4'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 54, time: "4' - 5'", velocidade: "13-15 km/h", esforço: "Forte" },
    { id: 55, time: "5' - 6'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 56, time: "6' - 7'", velocidade: "13-15 km/h", esforço: "Forte" },
    { id: 57, time: "7' - 8'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 58, time: "8' - 9'", velocidade: "16-18 km/h", esforço: "Máximo" },
    { id: 59, time: "9' - 10'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 60, time: "10' - 12'", velocidade: "13-15 km/h", esforço: "Forte" },
    {
      id: 61,
      time: "12' - 13'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 62, time: "13' - 14'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 63, time: "14' - 15'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
  level_5: [
    { id: 64, time: "0' - 1'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 65, time: "1' - 2'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 66,
      time: "2' - 3'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 67, time: "3' - 4'", velocidade: "13-15 km/h", esforço: "Forte" },
    { id: 68, time: "4' - 5'", velocidade: "16-18 km/h", esforço: "Máximo" },
    { id: 69, time: "5' - 6'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 70, time: "6' - 7'", velocidade: "16-18 km/h", esforço: "Máximo" },
    { id: 71, time: "7' - 8'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 72, time: "8' - 9'", velocidade: "13-15 km/h", esforço: "Forte" },
    { id: 73, time: "9' - 10'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 74,
      time: "10' - 11'",
      velocidade: "16-18 km/h",
      esforço: "Máximo",
    },
    { id: 75, time: "11' - 12'", velocidade: "13-15 km/h", esforço: "Forte" },
    {
      id: 76,
      time: "12' - 13'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 77, time: "13' - 14'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 78, time: "14' - 15'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
};

const hitData_25 = {
  level_0: [
    {
      id: 1,
      time: "0' - 1'",
      velocidade: "4-5 km/h",
      esforço: "Fácil",
    },
    {
      id: 2,
      time: "1' - 4'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    {
      id: 3,
      time: "4' - 5'",
      velocidade: "6-7 km/h",
      esforço: "Máximo",
    },
    { id: 4, time: "5' - 6'", velocidade: "4-5 km/h", esforço: "Fácil" },
    {
      id: 5,
      time: "6' - 7'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    { id: 6, time: "7' - 8'", velocidade: "6-7 km/h", esforço: "Máximo" },
    { id: 7, time: "8' - 9'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 8,
      time: "9' - 11'",
      velocidade: "4-5 km/h",
      esforço: "Fácil",
    },
    { id: 9, time: "11' - 12'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 10,
      time: "12' - 13'",
      velocidade: "6-7 km/h",
      esforço: "Máximo",
    },
    { id: 11, time: "13' - 15'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 12, time: "15' - 17'", velocidade: "4-5 km/h", esforço: "Fácil" },
    { id: 13, time: "17' - 20'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 14, time: "20' - 21'", velocidade: "6-7 km/h", esforço: "Máximo" },
    { id: 15, time: "21' - 22'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 16, time: "22' - 23'", velocidade: "6-7 km/h", esforço: "Máximo" },
    { id: 17, time: "23' - 24'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 18, time: "24' - 25'", velocidade: "4-5 km/h", esforço: "Fácil" },
  ],
  level_1: [
    {
      id: 19,
      time: "0' - 1'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
    {
      id: 20,
      time: "1' - 4'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    {
      id: 21,
      time: "4' - 5'",
      velocidade: "10-12 km/h",
      esforço: "Máximo",
    },
    { id: 22, time: "5' - 6'", velocidade: "5-6 km/h", esforço: "Fácil" },
    {
      id: 23,
      time: "6' - 7'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    { id: 24, time: "7' - 8'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 25, time: "8' - 9'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 26,
      time: "9' - 11'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
    { id: 27, time: "11' - 12'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 28,
      time: "12' - 13'",
      velocidade: "10-12 km/h",
      esforço: "Máximo",
    },
    { id: 29, time: "13' - 15'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 30, time: "15' - 17'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 31, time: "17' - 20'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 32, time: "20' - 21'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 33, time: "21' - 22'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 34, time: "22' - 23'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 35, time: "23' - 24'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 36, time: "24' - 25'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
  level_2: [
    {
      id: 37,
      time: "0' - 1'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
    {
      id: 38,
      time: "1' - 3'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    {
      id: 39,
      time: "3' - 4'",
      velocidade: "10-12 km/h",
      esforço: "Máximo",
    },
    { id: 40, time: "4' - 6'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 41,
      time: "6' - 7'",
      velocidade: "10-12 km/h",
      esforço: "Máximo",
    },
    { id: 42, time: "7' - 9'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 43, time: "9' - 10'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 44,
      time: "10' - 11'",
      velocidade: "10-12 km/h",
      esforço: "Máximo",
    },
    { id: 45, time: "11' - 14'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 46,
      time: "14' - 15'",
      velocidade: "10-12 km/h",
      esforço: "Máximo",
    },
    { id: 47, time: "15' - 16'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 48, time: "16' - 18'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 49, time: "18' - 19'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 50, time: "19' - 20'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 51, time: "20' - 21'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 52, time: "21' - 22'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 53, time: "22' - 24'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 54, time: "24' - 25'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
  level_3: [
    {
      id: 55,
      time: "0' - 1'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
    {
      id: 56,
      time: "1' - 2'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    {
      id: 57,
      time: "2' - 4'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 58, time: "4' - 5'", velocidade: "13-15 km/h", esforço: "Máximo" },
    {
      id: 59,
      time: "5' - 6'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
    {
      id: 60,
      time: "6' - 8'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 61, time: "8' - 9'", velocidade: "13-15 km/h", esforço: "Máximo" },
    {
      id: 62,
      time: "9' - 11'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    {
      id: 63,
      time: "11' - 12'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    {
      id: 64,
      time: "12' - 13'",
      velocidade: "13-15 km/h",
      esforço: "Máximo",
    },
    { id: 65, time: "13' - 15'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 66, time: "15' - 16'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 67,
      time: "16' - 18'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 68, time: "18' - 20'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 69,
      time: "20' - 22'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 70, time: "22' - 23'", velocidade: "13-15 km/h", esforço: "Máximo" },
    { id: 71, time: "23' - 24'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 72, time: "24' - 25'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
  level_4: [
    {
      id: 55,
      time: "0' - 1'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
    {
      id: 56,
      time: "1' - 3'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    {
      id: 57,
      time: "3' - 5'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 58, time: "5' - 6'", velocidade: "13-15 km/h", esforço: "Forte" },
    {
      id: 59,
      time: "6' - 8'",
      velocidade: "5-6 km/h",
      esforço: "Moderado Alto",
    },
    {
      id: 60,
      time: "8' - 9'",
      velocidade: "16-18 km/h",
      esforço: "Máximo",
    },
    { id: 61, time: "9' - 11'", velocidade: "13-15 km/h", esforço: "Moderado" },
    {
      id: 62,
      time: "11' - 12'",
      velocidade: "7-9 km/h",
      esforço: "Forte",
    },
    {
      id: 63,
      time: "12' - 14'",
      velocidade: "10-12 km/h",
      esforço: "Fácil",
    },
    {
      id: 64,
      time: "14' - 15'",
      velocidade: "13-15 km/h",
      esforço: "Forte",
    },
    {
      id: 65,
      time: "15' - 17'",
      velocidade: "5-6 km/h",
      esforço: "Moderado Alto",
    },
    { id: 66, time: "17' - 18'", velocidade: "7-9 km/h", esforço: "Fácil" },
    {
      id: 67,
      time: "18' - 20'",
      velocidade: "10-12 km/h",
      esforço: "Moderado",
    },
    {
      id: 68,
      time: "20' - 21'",
      velocidade: "7-9 km/h",
      esforço: "Moderado Alto",
    },
    {
      id: 69,
      time: "21' - 22'",
      velocidade: "10-12 km/h",
      esforço: "Forte",
    },
    {
      id: 70,
      time: "22' - 24'",
      velocidade: "13-15 km/h",
      esforço: "Moderado",
    },
    { id: 71, time: "24' - 24'", velocidade: "7-9 km/h", esforço: "Fácil" },
  ],
  level_5: [
    {
      id: 72,
      time: "0' - 1'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
    {
      id: 74,
      time: "1' - 3'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    {
      id: 75,
      time: "3' - 4'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    {
      id: 76,
      time: "4' - 6'",
      velocidade: "13-15 km/h",
      esforço: "Forte",
    },
    {
      id: 77,
      time: "6' - 7'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 78, time: "7' - 8'", velocidade: "16-18 km/h", esforço: "Máximo" },
    {
      id: 79,
      time: "8' - 9'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
    {
      id: 80,
      time: "9' - 10'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    {
      id: 81,
      time: "10' - 11'",
      velocidade: "13-15 km/h",
      esforço: "Forte",
    },
    {
      id: 82,
      time: "11' - 13'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 83, time: "13' - 14'", velocidade: "16-18 km/h", esforço: "Máximo" },
    {
      id: 84,
      time: "14' - 16'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
    {
      id: 85,
      time: "16' - 18'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    {
      id: 86,
      time: "18' - 20'",
      velocidade: "13-15 km/h",
      esforço: "Forte",
    },
    {
      id: 87,
      time: "20' - 22'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 88, time: "22' - 23'", velocidade: "16-18 km/h", esforço: "Máximo" },
    { id: 89, time: "23' - 24'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 89, time: "23' - 24'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
};

export { hitData_10, hitData_15, hitData_25 };
