const hitData = {
  level_0: [
    {
      id: 1,
      time: "0' - 1'",
      velocidade: "4-5 km/h",
      esforço: "Fácil",
    },
    {
      id: 2,
      time: "1' - 3'",
      velocidade: "5-6 km/h",
      esforço: "Moderado",
    },
    {
      id: 3,
      time: "3' - 4'",
      velocidade: "6-7 km/h",
      esforço: "Máximo",
    },
    { id: 4, time: "4' - 5'", velocidade: "4-5 km/h", esforço: "Fácil" },
    { id: 5, time: "5' - 6'", velocidade: "5-6 km/h", esforço: "Moderado" },
    { id: 6, time: "6' - 7'", velocidade: "4-5 km/h", esforço: "Fácil" },
    { id: 7, time: "7' - 8'", velocidade: "6-7 km/h", esforço: "Máximo" },
    { id: 8, time: "8' - 9'", velocidade: "5-6 km/h", esforço: "Moderado" },
    { id: 9, time: "9' - 10'", velocidade: "4-5 km/h", esforço: "Fácil" },
  ],
  level_1: [
    { id: 10, time: "0' - 1'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 11, time: "1' - 3'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 12, time: "3' - 4'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 13, time: "4' - 5'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 14, time: "5' - 6'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 15, time: "6' - 7'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 16, time: "7' - 8'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 17, time: "8' - 9'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 18, time: "9' - 10'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
  level_2: [
    { id: 19, time: "0' - 1'", velocidade: "5-6 km/h", esforço: "Fácil" },
    {
      id: 100,
      time: "1' - 3'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    { id: 20, time: "3' - 4'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 21, time: "4' - 5'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 22, time: "5' - 6'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 23, time: "6' - 7'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 24, time: "7' - 8'", velocidade: "10-12 km/h", esforço: "Máximo" },
    { id: 25, time: "8' - 9'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 26, time: "9' - 10'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
  level_3: [
    { id: 27, time: "0' - 1'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 28, time: "1' - 2'", velocidade: "5-6 km/h", esforço: "Moderado" },
    {
      id: 29,
      time: "2' - 3'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    { id: 30, time: "3' - 4'", velocidade: "13-15 km/h", esforço: "Máximo" },
    { id: 31, time: "4' - 5'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 32, time: "5' - 6'", velocidade: "13-15 km/h", esforço: "Máximo" },
    { id: 33, time: "6' - 7'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 34, time: "7' - 8'", velocidade: "13-15 km/h", esforço: "Máximo" },
    { id: 35, time: "8' - 9'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 36, time: "9' - 10'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
  level_4: [
    { id: 37, time: "0' - 1'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 38, time: "1' - 2'", velocidade: "7-9 km/h", esforço: "Moderado" },
    {
      id: 39,
      time: "2' - 3'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    {
      id: 40,
      time: "3' - 4'",
      velocidade: "13-15 km/h",
      esforço: "Forte",
    },
    { id: 41, time: "4' - 5'", velocidade: "5-6 km/h", esforço: "Fácil" },
    { id: 42, time: "5' - 6'", velocidade: "13-15 km/h", esforço: "Forte" },
    {
      id: 43,
      time: "6' - 7'",
      velocidade: "7-8 km/h",
      esforço: "Moderado",
    },
    {
      id: 44,
      time: "7' - 8'",
      velocidade: "16-18 km/h",
      esforço: "Máximo",
    },
    {
      id: 45,
      time: "8' - 9'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    {
      id: 46,
      time: "9' - 10'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
  ],
  level_5: [
    {
      id: 47,
      time: "0' - 1'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
    {
      id: 48,
      time: "1' - 2'",
      velocidade: "7-9 km/h",
      esforço: "Moderado",
    },
    {
      id: 49,
      time: "2' - 3'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    {
      id: 50,
      time: "3' - 4'",
      velocidade: "16-18 km/h",
      esforço: "Máximo",
    },
    {
      id: 51,
      time: "4' - 5'",
      velocidade: "5-6 km/h",
      esforço: "Fácil",
    },
    {
      id: 52,
      time: "5' - 6'",
      velocidade: "16-18 km/h",
      esforço: "Máximo",
    },
    {
      id: 53,
      time: "6' - 7'",
      velocidade: "10-12 km/h",
      esforço: "Moderado Alto",
    },
    {
      id: 54,
      time: "7' - 8'",
      velocidade: "16-18 km/h",
      esforço: "Máximo",
    },
    { id: 55, time: "8' - 9'", velocidade: "7-9 km/h", esforço: "Moderado" },
    { id: 56, time: "9' - 10'", velocidade: "5-6 km/h", esforço: "Fácil" },
  ],
};

export { hitData };
