export const routeCodes = {
  HOME: "Home",
  EXERCISES: "Exercises",
  HIT: "Hit",
  PROFILE: "Profile",
  SELECT_EXERCISE: "SelectCategory",
  SELECTED_EXERCISE: "SelectedExercise",
  WORKOUT: "Workout",
  CHARGE: "Charge",
  NOTES: "Notes",
  TIMER_SELECT: "TimerSelect",
  SELECT_LEVEL: "SelectLevel",
  HIT_RESUME: "HitResume",
  LOGIN: "Login",
  REGISTER: "Register",
};
